<?php

namespace App\Services\Attendance;

use App\Contracts\AttendanceSource;
use App\Data\PunchRecord;
use Carbon\CarbonInterface;

/**
 * Wraps a pre-built list of PunchRecords (generated by AttendanceLogSeeder)
 * so the seeder exercises the same PunchIngestor path a real device will.
 */
class SampleAttendanceSource implements AttendanceSource
{
    /**
     * @param  PunchRecord[]  $records
     */
    public function __construct(private readonly array $records) {}

    public function punches(CarbonInterface $from, CarbonInterface $to): iterable
    {
        foreach ($this->records as $record) {
            if ($record->punchedAt->between($from, $to)) {
                yield $record;
            }
        }
    }
}
